### ISSUE TITLE
View Student Loans

### ISSUE THREAD

**Issue by AndyGabler** [frap129/cs471-project#12]
As a member of the registrar, I would like to see what students have loans and how much those loans are and be able to filter by student, school and bank.

**Acceptance Criteria**
User Action | Expected Result
------------ | -------------
Log in as registrar user | Login successful, forwarded to registrar portal.
Navigate to page to view loans | Screen appears, listing all student loans.
Select dropdown to filter by student | Options listed are only the students who appear in the loan table.
Select a student from the dropdown and hit "Search." | Results filtered to only show loans to specified student.
Select dropdown to filter by school | Options listed are only the schools that appear in the loan table.
Select a school from the dropdown and hit "Search." | Results filtered to only show loans to students who attend specified school.
Select dropdown to filter by bank | Options listed are only the banks that appear in the loan table.
Select a bank from the dropdown and hit "Search." | Results filtered to only show loans to students from specified bank.

**Comment by AndyGabler** [comment]
Here is a rough API design for this one.
![View_Loans_Registrar_Request](https://user-images.githubusercontent.com/39251444/116818439-560b5180-ab39-11eb-8db4-f01f003a7d1a.png)

**Comment by frap129** [comment]
My only blocker on this is that loans dont contain a school name. We can let this take forever to load by traversing all the students and then all of their loans, adding a school name property to the loans in the db, or not add this filter. Thoughts? @AndyGabler @tbolar18 (Tagging bolar in case we need to modify the loans table)

**Comment by AndyGabler** [comment]
@frap129 I found something that might be helpful.

Section 5.1 discusses manual queries in Spring. I think doing a query like this with a JOIN in it should accomplish this nicely. SQL queries tend to be fast enough. (I assume your problem was doing this in Java and doing 1 lookup per result)

https://www.baeldung.com/spring-data-jpa-query
