### ISSUE TITLE
Loan Information

### ISSUE THREAD

**Issue by AndyGabler** [frap129/cs471-project#16]
As a bank officer, I would like to see the financial information of everyone who has a loan with my bank

**Acceptance Criteria**
Bank officers have access to a special set of screens that list all students with loans from their bank, and all of the students’ financial information

**Comment by AndyGabler** [comment]
Here is a rough API design for this one.
![Loan_Detail_Request](https://user-images.githubusercontent.com/39251444/116818476-936fdf00-ab39-11eb-8ffe-96486b211e6a.png)

**Comment by TytanRock** [comment]
@AndyGabler 
Is the response JSON an array with the specified elements? Or is it indexing at `loanId`? The user story talks about wanting to see the information of everyone who has a loan but the API design allows for only a single person.

**Comment by TytanRock** [comment]
@AndyGabler How does the bankerId fit in with this? Should it be used to ensure that the banker has access to the loan?

**Comment by AndyGabler** [comment]
@TytanRock Yep. Exactly.
