### ISSUE TITLE
Login System

### ISSUE THREAD

**Issue by AndyGabler** [frap129/cs471-project#22]
**Description**
As a user of the system, I should be able to log in.

**Acceptance Criteria**
User Action | Expected Result
------------ | -------------
User types in bad credentials and submits the page. | Notice appears that the login information is incorrect.
User types in correct credentials and submits the page. | Redirected to user-specific page.

**Comment by AndyGabler** [comment]
Here is the rough request structure I was hoping to have between the frontend and backend.
![Login Request Structured](https://user-images.githubusercontent.com/39251444/116793178-1722c080-aa93-11eb-8594-e6be913bbf15.png)

**Comment by TytanRock** [comment]
PR #23 will close this on the backend portion.
Currently I'm able to provide a JSON with dummy data based on a POST request to the `/login` endpoint.
![image](https://user-images.githubusercontent.com/13025939/117160199-ea222680-ad8e-11eb-8c7f-1939009e5929.png)
I'd like some guidance on how to interface with the database to pull data from it based on the username and password.

Also, currently the return object always has the ability to provide studentInfo/bankInfo, but will be null in cases where it isn't applicable. This can probably be changed by creating studentResponse/bankResponse classes that extend a loginResponse with the appropriate info sections.

**Comment by AndyGabler** [comment]
@TytanRock Currently, the backend does not return student info or bank info. Could this be looked into?

**Comment by frap129** [comment]
This can be closed, right?

**Comment by TytanRock** [comment]
Yeah, I think this can since frontend and backend both allow for logins
