### ISSUE TITLE
Loan/bank officer view all active loans

### ISSUE THREAD

**Issue by TytanRock** [frap129/cs471-project#4]
As a loan officer/bank officer, I would like to have a list of all active loans and their current statuses

**Acceptance Criteria**
| User Action | System Response |
|---|---|
| Officer accesses loan web page | Web page prompts login |
| Officer logs in | Web page responds with either success or failure |
| Officer navigates to active loan page | Web page responds with list of all active loans, along with statuses of all loans |

**Comment by AndyGabler** [comment]
Here is a rough API design for this one. Please note, under each element of loan, we will also need a "studentId" tag.
![View_Loans_Banker_Request](https://user-images.githubusercontent.com/39251444/116818467-84892c80-ab39-11eb-9f4f-2175792fe738.png)

**Comment by frap129** [comment]
@AndyGabler Could we modify the API to pass the user role in the request? If we do, I'll be able to commonize all the code for returning a list of loans, instead of having separate implementations for each role

**Comment by AndyGabler** [comment]
@frap129 I assume you are referring to the separate registrar view loan API?

**Comment by frap129** [comment]
> @frap129 I assume you are referring to the separate registrar view loan API?

Yep, and when we'll inevitably need to add one for students to see their own loans. I guess we could just trust that the front end maintains the correct bank/school/student filter, but having the role would allow us to enforce those filters on the backend.

**Comment by AndyGabler** [comment]
So keep in mind, for the requests here and #12 , the frontend will only be able to use information it has from the Login API to make this request.

Here is how I had originally intended the values in each respective API to be populated. Keep in mind, the frontend has absolutely no access to the database; it can only send back values it was given by the backend.

| API | Value | Origin |
|---|---|---|
| Registrar | bankId | We will collect all banks on every loan after an initial request and condense them to a drop-down selection. |
| Registrar | studentId | We will collect all schools on every loan after an initial request and condense them to a drop-down selection. |
| Registrar | schoolName  | We will collect all schools on every loan after an initial request and condense them to a drop-down selection. |
| Bank/Loan Officer | bankId | This is the same bankId from the login under "bankInfo" (the screenshot in #4 says "bankerId", this is inconsistent with the login, apologies. It should be bankId) |
| Bank/Loan Officer | studentId | We will collect all students on every loan after an initial request and condense them to a drop-down selection. |
| Bank/Loan Officer | School | We will collect all schools on every loan after an initial request and condense them to a drop-down selection. |

If you can find a nice way to merge these and ensure the frontend has all the information it will need, I'm game! Keep in mind, during login, the frontend accepts the entire "bankInfo", so if you feel the need to add more metadata in there for us to use this API, feel free!

**Remark**
I typed out most of this comment before making the table. Yeah I think this can be condensed into one API.

**Comment by AndyGabler** [comment]
On the subject of including a role in the request, my question would be what difference it would make?

In either case where we do or don't send a user role, we're still trusting that the frontend did its due diligence before sending the request. PHP runs server-side so the "front-end" isn't exactly client-side where its validations and checks are subverted. I think the way the frontend collects the information to make the request should mean there won't be need to repeat validations in the backend (since the information is backend in origin).

**Comment by AndyGabler** [comment]
Actually, I think including a role might help if we decide bank people don't need to see loans of certain statuses and registrar people do (or vice versa). Just make sure @genocidalist know what validations are covered for us if you choose to make any.
