### ISSUE TITLE
Approve Loan

### ISSUE THREAD

**Issue by TytanRock** [frap129/cs471-project#49]
As a loan officer, I would like to approve a loan that is presented to me so that the student gets the money from the loan.

**Acceptance Criteria**
| Step | System Response|
|---|---|
| Officer navigates to loan page | System provides loan page |
| Officer clicks loan | System provides details of loan |
| Officer clicks *Approve* or "Deny" | System approves or denies loan and responds with success or failure |

**Comment by AndyGabler** [comment]
![image](https://user-images.githubusercontent.com/39251444/119724618-f43ebe80-be3c-11eb-91a4-16e7f7e81886.png)
Here is an API design. The expectation would be that the backend would be responsible for the following:
 * Check that the status of the loan is "PENDING"
 * Change the loans status to "APPROVED"
 * Query the user table and check that the banker supplied exists on the table with the role of "LOANOFFICER"
 * Ensure that the banker supplied is actually associated with the bank the loan is on
