### ISSUE TITLE
State Diagrams

### ISSUE THREAD

**Issue by TytanRock** [frap129/cs471-project#65]

**Comment by frap129** [comment]
Since we didn't complete the code, do we need to provide a full state diagram? I made one for the existing states, didnt add any states that planned features would have introduced.

**Comment by TytanRock** [comment]
I think only providing the states we have implemented is fine

**Comment by TytanRock** [comment]
Added in commit https://github.com/frap129/cs471-project/pull/69/commits/478876c9adadf7b6af691c7391d8c035e013b2b5
